Add AWS Resource Naming convention
future-architect/coding-standards pull request #42
Opened 2023-03-04 08:15 UTC by ma91n

AWSインフラ命名規則を追加しました

2023-03-04 08:16 UTC, ma91n commented on .devcontainer/devcontainer.json
> +    "args": {
`npm run format` による差分です

2023-03-04 08:16 UTC, ma91n commented on .editorconfig
> +end_of_line = lf
Windowsで作業したときに、改行コード設定で揺れたので追加しました。

2023-03-06 04:20 UTC, ota-meshi requested changes

2023-03-06 04:20 UTC, ota-meshi commented on documents/forAWSResource/README.md
> +- Word
`.github/workflows/GHPages.yml` に生成コマンドを追加して、以下のようにリンクしていただけますか？

```suggestion
- [Markdown](https://github.com/future-architect/coding-standards/blob/master/documents/forAWSResource/AWSインフラリソース命名規約.md)
- [HTML](https://github.com/future-architect/coding-standards/blob/gh-pages/resources/AWSインフラリソース命名規約.html)
- [Word](https://github.com/future-architect/coding-standards/raw/gh-pages/resources/AWSインフラリソース命名規約.docx)
```

2023-03-06 07:46 UTC, ota-meshi approved these changes
LGTM!

2023-03-06 12:47 UTC, merged

2023-03-06 13:12 UTC, shout-star commented on documents/forAWSResource/AWSインフラリソース命名規約.md
> +- 使用する文字は英数字に限定する。基本的には **キャメルケース (CamelCase)** 形式を推奨する
@ma91n 
キャメルケースではなくパスカルケースでは？